version: "3.8"

services:
  backend:
    build:
      context: ./
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_management
      MYSQL_USER: anup
      MYSQL_PASSWORD: anup@123
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
